const etude = {
    "Topologie en bus": "Un seul câble principal (bus) relie tous les appareils.",
    "Topologie en étoile": "Tous les périphériques sont connectés à un point central (commutateur ou hub).",
    "Topologie en anneau": "Les appareils sont connectés en boucle, les données circulent dans un sens déterminé.",
    "Topologie maillée": "Chaque nœud est connecté à plusieurs autres pour assurer une redondance maximale.",
    "Topologie en arbre": "Une hiérarchie de plusieurs topologies en étoile connectées à un niveau supérieur.",
    "LAN": "Local Area Network / Un réseau informatique qui couvre une petite zone géographique, comme un bureau, une maison ou une école.",
    "UTP": "Unshielded Twisted Pair (Paire torsadée non blindé) Type de câble réseau constitué de fils torsadés par paires pour réduire les interférences, mais sans blindage supplémentaire. Couramment utilisé pour Ethernet.",
    "BNC": "Bayonet Neill-Concelman (cable caoxial, cable des vieille tv)",
    "adresse MAC": "Media Access Control / Adresse physique unique attribuée à chaque carte réseau pour l’identification dans un réseau Ethernet.",
    "DNS": "Domain Name System / Service qui traduit les noms de domaine (ex. : www.google.com) en adresses IP compréhensibles par les ordinateurs.",
    "PAN": "Personal Area Network / Réseau informatique utilisé pour interconnecter des appareils proches d'une personne, comme un smartphone, une tablette et un ordinateur via Bluetooth ou Wi-Fi.",
    "BAN": "Body Area Network / 'réseau corporel', est un réseau sans fil de dispositifs intelligents portés sur ou autour du corps humain",
    "MAN": "Metropolitan Area Network / Réseau qui couvre une ville ou une grande agglomération, reliant plusieurs réseaux locaux (LAN).",
    "WAN": "Wide area network / Réseau qui couvre une grande zone géographique, reliant plusieurs LAN et MAN sur de longues distances (exemple : Internet).",
    "UTP": "Unshielded Twisted Pair (Paire torsadée non blindé) / Câble Ethernet utilisé pour les réseaux locaux, sans blindage supplémentaire contre les interférences.",
    "FTP": "File Transfer Protocol (Protocole de transfert de fichier ) Protocole utilisé pour transférer des fichiers entre un client et un serveur sur un réseau.",
    "STP": "Shielded Twisted Pair (Paire torsadée blindé) Variante du câble UTP, mais avec un blindage supplémentaire pour réduire les interférences électromagnétiques.",
    "IP": "Internet Protocol / Identifie et achemine les paquets de données sur un réseau via des adresses IP. / Routage des données sur Internet.",
    "HTTP": "HyperText Transfer Protocol / Protocole permettant d'afficher des pages web en échangeant des données entre un serveur et un navigateur. / Affichage des sites web.",
    "HTTPS": "HyperText Transfer Protocol Secure / Version sécurisée de HTTP qui chiffre les échanges entre l’utilisateur et le serveur via SSL/TLS. / Navigation sécurisée sur Internet.",
    "WWW": "World Wide Web / Service permettant d’accéder aux sites web via HTTP/HTTPS. / Accès et navigation sur le Web.",
    "TCP": "Transmission Control Protocol / Protocole assurant une transmission fiable des données en vérifiant leur réception et leur ordre. / Transmission fiable des données (Web, Email, Téléchargements).",
    "UDP": "User Datagram Protocol / Protocole rapide pour envoyer des données sans garantie de réception (ex : streaming, jeux en ligne). / Transmission rapide sans contrôle des erreurs (VoIP, Streaming).",
    "SMTP": "Simple Mail Transfer Protocol / Protocole utilisé pour l'envoi d'emails depuis un client vers un serveur de messagerie. / Envoi d'emails vers un serveur de messagerie.",
    "IMAP": "Internet Message Access Protocol / Protocole permettant de récupérer et synchroniser des emails stockés sur un serveur. / Récupération et gestion des emails sur un serveur.",
    "FTP": "File Transfer Protocol / Protocole permettant de transférer des fichiers entre un client et un serveur sur un réseau. / Transfert de fichiers sur un réseau (Hébergement web, partage de fichiers).",
    "Pare-feu matériel": "Un dispositif physique dédié à la sécurité du réseau. Il filtre le trafic AVANT qu’il n’atteigne les ordinateurs du réseau.(plus rapide)",
    "Pare-feu logiciel": "Une application installée sur un ordinateur ou un serveur qui surveille le trafic réseau et bloque les connexions suspectes.(peut ralentir l'ordinateur)",
    "CPU": "Central Processing Unit",
    "ALU": "Arithmetic Logic Unit",
    "CU": "Control Unit",
    "RAM": "Random Access Memory",
    "ROM": "Read-Only Memory",
    "PCB": "Printed Circuit Board",
    "BIOS": "Printed Circuit Board",
    "CMOS": "Complementay Metal-Oxide-Semiconductor",
    "GPU": "Graphics Processing Unit",
    "I/O": "Input/Output",
    "HDD": "Hard Disk Drive",
    "SSD": "Solid State Drive",
    "FPU": "Floating Point Unit",
    "DMA": "Direct Memory Access",
    "IRQ": "Interrupt Request",
    "FSB": "Front Side Bus",
    "PCI": "Peripheral Component Interconnect",
    "USB": "Universal Serial Bus",
    "NIC": "Network InterfaceCard",
    "RAID": "Redundant Array of Independent Disks",
    "CMOS Battery": "Pile CMOS",
    "PCIe": "Perpheral Compoent Interconnect Express",
    "USB-C": "Universal Serial Bus Type-C",
    "DIMM": "Dual Inline Memory Module",
    "SATA": "Serial ATA",
    "IDE": "Integrated Drive Electronics",
    "VGA": "Video Graphics Array",
    "Northbridge": "composant responsable de la gestion des communications entre l'unité centrale de traitement (UC) et la mémoire",
    "Southbridge": "Responsable de la gestion de divers périphériques connectés à l'ordinateur",
    "BSOD": "Bleu screen of death (ecran bleu quand le pc bug)",
    "Chipset": "(Northbridge + Southbridge) Ensemble de composants électroniques dans un ordinateur qui gère le flux de données entre le processeur, la mémoire et les périphériques",
    "Spouleur d'impression": "(Print Spooler) Il organise et met en file d'attente les documents à imprimer (à redémarrer en cas de bug avec l'imprimante)",
    "Quel est le but de la defragmentation ?": "Augmenter les performances du HDD",
    "GUI": "Graphique user interface",
    "MBR": "Master Boot Record - systèmes de gestion des partitions, fonctionne sur les systèmes BIOS, supporte une capacité maximale de disque de 2 To, permet de créer jusqu'à 4 partitions principales",
    "GPT": "GUID Partition Table - systèmes de gestion des partitions, fonctionne sur les systèmes UEFI, peut gérer jusqu'à 128 partitions primaires",
    "Office de Linux": "Libre Office",
    "Licence publique de Linux": "GNU",
    "UEFI": "(Unified Extensible Firmware Interface) Interface moderne qui remplace le BIOS",
    "Secure Boot": "Protège contre les logiciels malveillants modifiant le processus de démarrage",
    "SPDIF": "Sony/Philips Digital Interface Format - norme utilisée pour transmettre des signaux audio numériques entre différents appareils",
    "TOSLINK": "Interface utilisée pour transmettre des signaux audio numériques via un câble optique",
    "caloduc": "Tube hermétique contenant un fluide pour transporter la chaleur d'un point à un autre",
    "jeu d'instruction": "Instruction set - l'ensemble des commandes ou instructions qu'un processeur peut comprendre et exécuter, les processeurs 64 bits peuvent généralement exécuter des instructions 32 bits grâce à une compatibilité ascendante",
    "UPS": "Uninterruptible Power Supply (ou en français onduleur) - dispositif qui fournit une alimentation électrique de secours en cas de coupure de courant",
    "mémoire cache": "Type de mémoire rapide située entre le processeur et la RAM ou directement dans le processeur, réduit le temps d'accès aux données fréquemment utilisées",
    "EEPROM": "(Electrically Erasable Programmable Read-Only Memory) Utilisée pour modifier ou mettre à jour le BIOS, ce qu'on appelle un flashage du BIOS",
    "BIOS": "Basic Input/Output System",
    "POST": "(Power-On Self-Test) Le BIOS exécute une série de tests pour s'assurer que tous les composants matériels essentiels fonctionnent correctement"
};