const etude = {
    "Topologie en bus": "Un seul câble principal (bus) relie tous les appareils.",
    "Topologie en étoile": "Tous les périphériques sont connectés à un point central (commutateur ou hub).",
    "Topologie en anneau": "Les appareils sont connectés en boucle, les données circulent dans un sens déterminé.",
    "Topologie maillée": "Chaque nœud est connecté à plusieurs autres pour assurer une redondance maximale.",
    "Topologie en arbre": "Une hiérarchie de plusieurs topologies en étoile connectées à un niveau supérieur.",
    "LAN": "Réseau local / Un réseau informatique qui couvre une petite zone géographique, comme un bureau, une maison ou une école.",
    "UTP": "Paire torsadée non blindée / Type de câble réseau constitué de fils torsadés par paires pour réduire les interférences, mais sans blindage supplémentaire. Couramment utilisé pour Ethernet.",
    "BNC": "Connecteur BNC / Connecteur utilisé principalement pour les câbles coaxiaux dans les réseaux anciens et pour les équipements vidéo (caméras, TV).",
    "MAC": "Adresse MAC / Adresse physique unique attribuée à chaque carte réseau pour l’identification dans un réseau Ethernet.",
    "DNS": "Système de noms de domaine / Service qui traduit les noms de domaine (ex. : www.google.com) en adresses IP compréhensibles par les ordinateurs.",
    "PAN": "Réseau personnel / Réseau informatique utilisé pour interconnecter des appareils proches d'une personne, comme un smartphone, une tablette et un ordinateur via Bluetooth ou Wi-Fi.",
    "BAD": "Bande d’accès direct / Terme utilisé dans certains contextes pour désigner un accès rapide aux données sans passer par des étapes intermédiaires. (Peu courant dans les réseaux)",
    "MAN": "Réseau métropolitain / Réseau qui couvre une ville ou une grande agglomération, reliant plusieurs réseaux locaux (LAN).",
    "WAN": "Réseau étendu / Réseau qui couvre une grande zone géographique, reliant plusieurs LAN et MAN sur de longues distances (exemple : Internet).",
    "UTP": "Paire torsadée non blindée / Câble Ethernet utilisé pour les réseaux locaux, sans blindage supplémentaire contre les interférences.",
    "FTP": "Protocole de transfert de fichiers / Protocole utilisé pour transférer des fichiers entre un client et un serveur sur un réseau.",
    "STP": "Paire torsadée blindée / Variante du câble UTP, mais avec un blindage supplémentaire pour réduire les interférences électromagnétiques.",
    "IP": "Internet Protocol / Identifie et achemine les paquets de données sur un réseau via des adresses IP. / Routage des données sur Internet.",
    "HTTP": "HyperText Transfer Protocol / Protocole permettant d'afficher des pages web en échangeant des données entre un serveur et un navigateur. / Affichage des sites web.",
    "HTTPS": "HyperText Transfer Protocol Secure / Version sécurisée de HTTP qui chiffre les échanges entre l’utilisateur et le serveur via SSL/TLS. / Navigation sécurisée sur Internet.",
    "WWW": "World Wide Web / Service permettant d’accéder aux sites web via HTTP/HTTPS. / Accès et navigation sur le Web.",
    "TCP": "Transmission Control Protocol / Protocole assurant une transmission fiable des données en vérifiant leur réception et leur ordre. / Transmission fiable des données (Web, Email, Téléchargements).",
    "UDP": "User Datagram Protocol / Protocole rapide pour envoyer des données sans garantie de réception (ex : streaming, jeux en ligne). / Transmission rapide sans contrôle des erreurs (VoIP, Streaming).",
    "SMTP": "Simple Mail Transfer Protocol / Protocole utilisé pour l'envoi d'emails depuis un client vers un serveur de messagerie. / Envoi d'emails vers un serveur de messagerie.",
    "IMAP": "Internet Message Access Protocol / Protocole permettant de récupérer et synchroniser des emails stockés sur un serveur. / Récupération et gestion des emails sur un serveur.",
    "FTP": "File Transfer Protocol / Protocole permettant de transférer des fichiers entre un client et un serveur sur un réseau. / Transfert de fichiers sur un réseau (Hébergement web, partage de fichiers).",
    "Pare-feu matériel": "Un dispositif physique dédié à la sécurité du réseau. Il filtre le trafic AVANT qu’il n’atteigne les ordinateurs du réseau.(plus rapide)",
    "Pare-feu logiciel": "Une application installée sur un ordinateur ou un serveur qui surveille le trafic réseau et bloque les connexions suspectes.(peut ralentir l'ordinateur)"
};